#!/bin/bash

# the line above is called a "shebang" (pronounced "shabang")
# it tells the computer how to interpret the script, e.g.
# which scripting language to use

# we can now run commands in a sequence, as if we were typing
# them into the command line. A comment above each command will
# explain what is happening:


# SCRIPT
# =============================================================

# print a message
printf "Hello, I am a generated by the script 'scripting_demo_1.sh'"

# =============================================================
# END OF SCRIPT

# IMPORTANT!:
# Note: we need to run the command `chmod +rwx [script_name.sh]` in
# the terminal to make the script executable. The chmod command changes
# the file permissions "rwx" grants full permissions (read, write, 
# execute).

# To run the script, after changing the permissions, we navigate to the
# directory that contains it, and use `./[script_name.sh]`


